### ISSUE TITLE
Button, Modal 컴포넌트 제작

### ISSUE THREAD

**Issue by sangseophwang** [PreOnBoarding-Team17/Week2_Messenger#6]
## ❗️이슈 주제
Button, Modal 컴포넌트 제작

## ✔︎ 해야 할 일

- [x] 종류별 버튼 생성
- [x] 첫 화면, 로그아웃 시 나타나는 모달 구현
- [x] 모달 리덕스 생성
- [x] 모달에서 닉네임 입력하고 제출했을 때 이벤트 구현
- [x] 버튼 hover, active 효과 구현

**Comment by som-syom** [comment]
Modal 이 닉네임 입력하는 부분도 있지만 메세지 삭제하는 부분에서도 있는데
화면 위에 띄워지는 Modal 틀만 제작하고
LoginModal, DeleteModal 에서 가져다 쓰는 방식으로 제작하면 어떨까요???

**Comment by sangseophwang** [comment]
> 

넵 참고해서 만들어볼께요 :)
